[package]
name = "reqwest-oauth1"
version = "0.1.0"
authors = ["Karno <karnoroid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.8"
oauth1-request = "0.3.2"
http = "0.2.1"
serde_urlencoded = "0.6.0"
serde = "1.0.116"
url = "2.1.1"
